services:
  timescaledb:
    image: timescale/timescaledb-ha:pg16
    container_name: djka_db
    environment:
      - POSTGRES_PASSWORD=djka_rahasia
      - POSTGRES_USER=djka_admin
      - POSTGRES_DB=djka_monitoring
    ports:
      - "5434:5432"
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
    restart: always

  mqtt-broker:
    image: eclipse-mosquitto:2
    container_name: djka_mqtt
    ports:
      - "1883:1883"
      - "9002:9001"
    volumes:
      - ./docker/mosquitto/config:/mosquitto/config
      - ./docker/mosquitto/data:/mosquitto/data
      - ./docker/mosquitto/log:/mosquitto/log
    restart: always

  redis:
    image: redis:7
    container_name: djka_redis
    ports:
      - "6378:6379"
    restart: always

volumes:
  timescaledb_data:
